[model]
name = "Dora AI Agent"
api_url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"

[mcp]
[[mcp.server]]
name = "MCP server name"
protocol = "stdio"
command = "MCP server path"
args = [" "]