name = "MCP Server Example"
version = "0.1.0"

# You can set your custom listen address and endpoint here.
# Default listen address is "0.0.0.0:8008" and endpoint is "mcp".
listen_addr = "0.0.0.0:8181"
endpoint = "mcp"

# Too definition structure: https://modelcontextprotocol.io/docs/concepts/tools#tool-definition-structure
[[mcp_tools]]
name = "counter_decrement"
input_schema = "empty_object.json"
output = "counter"
[mcp_tools.annotations]
title = "decrement current value of the counter"

[[mcp_tools]]
name = "counter_increment"
input_schema = "empty_object.json"
output = "counter"
[mcp_tools.annotations]
title = "Increment current value of the counter"

[[mcp_tools]]
name = "counter_get_value"
input_schema = "empty_object.json"
output = "counter"
[mcp_tools.annotations]
title = "Get the current value of the counter"