name = "MCP Server Example"
version = "0.1.0"

[[mcp_tools]]
name = "counter decrement"
args = []
input_schema = "empty_object.json"
node_id = "counter"

[[mcp_tools]]
name = "counter increment"
args = []
input_schema = "empty_object.json"
node_id = "counter"

[[mcp_tools]]
name = "counter get value"
args = []
input_schema = "empty_object.json"
node_id = "counter"