name = "MCP Server Example"
version = "0.1.0"

# You can set your custom listen address and endpoint here.
# Default listen address is "0.0.0.0:8008" and endpoint is "mcp".
listen_addr = "0.0.0.0:8181"
endpoint = "mcp"

[[mcp_tools]]
name = "counter_decrement"
args = []
input_schema = "empty_object.json"
node_id = "counter"

[[mcp_tools]]
name = "counter_increment"
args = []
input_schema = "empty_object.json"
node_id = "counter"

[[mcp_tools]]
name = "counter_get_value"
args = []
input_schema = "empty_object.json"
node_id = "counter"