name = "MCP Server Example"
version = "0.1.0"

[[mcp_tools]]
name = "Counter"
args = [" "]
input_schema = "counter.json"

# [[mcp_tools]]
# name = "Weather"
# args = [" "]
# input_schema = "counter.json"